apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-iwg4
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0046-tenant/tkrw-pr712-0075-0046-app/devfile-sample-iwg4@sha256:945bef3af58d4c5c97c7c27b4f915ece0b2f17481cfb4d91c1fb3ed0b680a506
        name: my-nodejs
        resources: {}
status: {}
